### ISSUE TITLE
Video Types

### ISSUE THREAD

**Issue by mkernal** [tubepress/tubepress#587]
Hello,

Currently you ONLY have YouTube & Vimeo video sources.
PLEASE, PLEASE, PRETTY PLEASE add more

**Comment by ehough** [comment]
LiveLeak, Bandcamp, Metacafe, Break, viewster, and Crackle don't appear to have an API at this time so we won't be able to utilize them.

Ustream has an API but it seems to be paid-only, so this won't be implemented unless there's sufficient demand from TubePress users.

Vube appears to be inactive.

Dailymotion is nearing completion and we'll close #611 when it's released.

If anyone has another video provider they'd like to see, please open a new issue. Thanks
