### ISSUE TITLE
Responsive video when Tubepress Express is embedded in a site

### ISSUE THREAD

**Issue by Daniel30fans** [tubepress/tubepress#599]

**Comment by ehough** [comment]
This is now implemented in TubePress Express. If you want to get it to work on any of your existing TubePress Express galleries, however, you'll need to update them to use the "new" default TubePress theme:

1. Log in to TubePress Express
1. Click "Edit" for one of your existing galleries.
1. On the "Theme" tab, ensure that "Default" is selected.

All new TubePress Express galleries will use this theme by default, so no action is required.
