### ISSUE TITLE
Conflict with Visual Composer - Shortcode display bug

### ISSUE THREAD

**Issue by brettshumaker** [tubepress/tubepress#600]
tldr; version: Tubepress does not use the standard 'add_shortcode' method for utilizing WordPress shortcodes. This is somehow causing the TubePress shortcode to be rendered incorrectly in certain circumstances within Visual Composer.

You can see all info about this bug in the forum here: http://community.tubepress.com/topic/5057-help-tubepress-shortcode-doesnt-work-in-visual-composer-correctly/

**Comment by ehough** [comment]
This has been resolved in TubePress 4.0.3. TubePress now uses `add_shortcode` and the rest of the shortcode API, so it should integrate perfectly with other WP plugins and themes.

You can download the free trial from [here](http://community.tubepress.com/files/file/18-tubepress-free-trial/) or TubePress Pro from [here](http://community.tubepress.com/files/file/11-tubepress-pro/).
