### ISSUE TITLE
Allow searching of a playlist not just a user

### ISSUE THREAD

**Issue by asirota** [tubepress/tubepress#604]
Currently you can do this:

[tubepress output="searchResults" searchProvider="youtube" searchResultsRestrictedToUser="InsightaaS"]

to restrict the search to a youtube user.

It would be great to restrit the search to one or more playlists, one or more users and one or more video ids.

So something like this

[tubepress output="searchResults" searchProvider="youtube" searchResultsRestrictedToUser="InsightaaS" playlistValue="GV930MjYXW1OoX7-mDQ2uwm3wPcwAJxh"]
Thanks!

**Comment by ehough** [comment]
YouTube's API does not provide us with the ability to restrict search results to a playlist [1], and it seems unlikely that they'll add this capability anytime soon. You may file a feature request with YouTube [2] but frankly they are not very responsive.

In theory TubePress could pull back *all* items from the playlist, internally process the search, and display the results. But this would require writing a significant amount of delicate code and probably lead to inaccurate search results (we're not Google/YouTube).

Given all of that, I'm closing this issue. If the demand for this feature increases in the future, we can take another look.

[1] https://developers.google.com/youtube/v3/docs/search/list

[2] https://code.google.com/p/gdata-issues/issues/list?can=2&q=API%3AYouTube&colspec=API+ID+Type+Status+Priority+Stars+Summary&cells=tiles
