### ISSUE TITLE
not compatible with Hide My WP plugin

### ISSUE THREAD

**Issue by ehough** [tubepress/tubepress#609]
TubePress does not work properly when used in conjunction with [Hide My WP](http://codecanyon.net/item/hide-my-wp-no-one-can-know-you-use-wordpress/4177158), likely due to the fact that TubePress is unable to detect that it's running in a WordPress installation.

**Comment by afrttoh** [comment]
Its working fine here with latest tubepress and hide_my_wp

**Comment by ehough** [comment]
I can confirm that this bug is invalid.
