### ISSUE TITLE
Not compatible with Jetpack's Photon feature

### ISSUE THREAD

**Issue by ehough** [tubepress/tubepress#615]
[Jetpack's Photon](https://jetpack.me/support/photon/) does not play nice at all with TubePress. We either need to note this in the documentation or come up with a workaround to stop Photon from mangling TubePress's thumbnails.

**Comment by Ravsiyan** [comment]
Any updates on this?

**Comment by ehough** [comment]
No updates yet, sorry. The workaround for now is to disable Photon. We will have a better solution in place as soon as possible.

**Comment by ehough** [comment]
Photon [has a filter](https://github.com/Automattic/jetpack/blob/master/functions.photon.php#L27) that should allow us to disable the feature for TubePress-generated thumbnails. The logic could be as simple as: if image URL is from YouTube/Vimeo CDN, then do not use photon.

We're releasing TubePress 5.0.0 in the next day or so. I've scheduled this down as a todo for 5.0.1.

**Comment by ehough** [comment]
TubePress 5.0.1 has just been released and includes a fix for this issue. Please [update](http://support.tubepress.com/customer/en/portal/articles/2032975-manual-upgrade-procedure) and let us know  if you continue to experience trouble. Thanks!
